export const projects = [
  {
    key: 'brand',
    title: 'brand',
    bullets: [
      'Brand Strategy',
      '360° Creative',
      'Art Direction',
      'Copywriting',
      'Editing',
      'Motion Graphics',
      'DTP',
    ],
    color: '#2E7E6F',
    accent: '#0E3C33',
    text:  '#FFFFFF',
    stickerSrc: '/svg/lets-go.svg',
    angle: 5, // fixed rotation like the reference
  },
  {
    key: 'social',
    title: 'social',
    bullets: [
      'Social Media Strategy',
      'Social Media Creative',
      'TikTok / Shortform',
      'Influencer Campaigns',
      'Scheduling Support',
    ],
    color: '#8FB6FF',
    accent: '#213B72',
    text:  '#080807',
    stickerSrc: '/svg/good-vibes.svg',
    angle: 2.5,
  },
  {
    key: 'activations',
    title: 'activations',
    bullets: ['Activation Strategy', 'Event Planning', 'Art Direction', 'Production'],
    color: '#FF7A3C',
    accent: '#5E240A',
    text:  '#080807',
    stickerSrc: '/svg/fistbumb.svg',
    angle: 0,
  },
  {
    key: 'video',
    title: 'video production',
    bullets: ['Campaign video', 'Branded content', 'Social content', 'Marketing material'],
    color: '#8E2747',
    accent: '#F7D8E1',
    text:  '#FFFFFF',
    stickerSrc: '/svg/cute.svg',
    angle: -2.5,
  },
  {
    key: 'partners',
    title: 'with partners',
    bullets: ['PR / Journalism', '3D / VFX', 'Food styling', 'Photography'],
    color: '#E7C4EE',
    accent: '#4C2B55',
    text:  '#080807',
    stickerSrc: '/svg/camera.svg',
    angle: -5,
  },
];
