export const projects = [
  {
    key: 'brand',
    title: 'Web design',
    bullets: [
      'Brand Discovery',
      'UX Research & Wireframes',
      'High-Fidelity UI (Figma)',
      'Design Systems & Style Guides',
      'Conversion-Focused Landing Pages',
    ],
    color: '#2D7864',
    accent: '#0E3C33',
    text:  '#FFFFFF',
    stickerSrc: '/svg/love.svg',
    angle: 5, // fixed rotation like the reference
  },
  {
    key: 'social',
    title: 'Web dev',
    bullets: [
      'Next.js + Tailwind Builds',
      'CMS integration',
      'GSAP / Framer Interactions',
      'Performance Tuning (CWV 90+)',
      'API Integrations & Webhooks',
    ],
    color: '#82A0FF',
    accent: '#213B72',
    text:  '#080807',
    stickerSrc: '/svg/fistbumb.svg',
    angle: 2.5,
  },
  {
    key: 'activations',
    title: 'Animations',
    bullets: [ 
      'UI Micro-Interactions',
      'SVG / JSON Animations',
      'Scroll-Triggered Stories (GSAP)',
      'Kinetic Typography',
      '3D Interactions (Three.js)',
    ],
    color: '#F5693C',
    accent: '#5E240A',
    text:  '#080807',
    stickerSrc: '/svg/good-vibes.svg',
    angle: 0,
  },
  {
    key: 'video',
    title: 'Social media',
    bullets: ['Reels / TikTok / Shorts',
      'Storyboarding & Scripting', 'Branded content', 'Social content', 'Marketing material'],
    color: '#A0325A',
    accent: '#F7D8E1',
    text:  '#FFFFFF',
    stickerSrc: '/svg/cute.svg',
    angle: -2.5,
  },
  {
    key: 'partners',
    title: 'product design',
    bullets: [  'MVP Planning',
  'User Flows & Wireframes',
  'Clickable Prototypes',
  'Clean UI Design',
  'Usability Checks',],
    color: '#F0BEFA',
    accent: '#4C2B55',
    text:  '#080807',
    stickerSrc: '/svg/camera.svg',
    angle: -5,
  },
];
